### ISSUE TITLE
Use terminal-notifier.app on macOS

### ISSUE THREAD

**Issue by antonmedv** [jolicode/JoliNotif#34]
Use [terminal-notifier.app](https://github.com/mikaelbr/node-notifier/tree/master/vendor/terminal-notifier.app) for better notifier on macos.

**Comment by pyrech** [comment]
Hi :)

I'm not sure I understand your issue. `terminal-notifier` is already supported (the driver is [here](https://github.com/jolicode/JoliNotif/blob/master/src/Notifier/TerminalNotifierNotifier.php)) and will be used by JoliNotif if it's installed on your system.

If you meant to embed the mac application to always have it available, I'm not sure it's possible. Some binaries are already embedded inside JoliNotif (see the [bin directory](https://github.com/jolicode/JoliNotif/tree/master/bin)) but it's currently only for Windows notifiers. The reason is simple: actually, JoliNotif can be embedded inside phar applications, so it needs to first extract all the files of the binary from the phar before executing it. Those files are extracted on temp directory of the system but for security reasons, Unix systems forbid to execute binaries inside its temp directory.

If this is really what you propose, maybe we could embed `terminal-notifier`'s binary and only propose to use it when not in a phar.

**Comment by antonmedv** [comment]
Ohh, i see. Thanks. Did know about phars.
