### ISSUE TITLE
Replace Windows 8+ notifier?

### ISSUE THREAD

**Issue by pyrech** [jolicode/JoliNotif#45]
In https://github.com/mikaelbr/node-notifier/commit/61fafc50c387fab2c53f3883af7d53f53209b0c3, they changed the replaced the windows 8+ notifier (Toaster) by a new one: https://github.com/KDE/snoretoast
Check whether we would benefit to switch to it inside JoliNotif

**Comment by pyrech** [comment]
Maybe not https://github.com/mikaelbr/node-notifier/issues/206#issuecomment-345502476

**Comment by owenvoke** [comment]
I know this is really old, but I've created a Snoretoast adapter after finding that Toaster no longer appears to work when multiple flags are provided.

Here is the branch for the adapter: https://github.com/jolicode/JoliNotif/compare/master...owenvoke:feature/snoretoast

It looks like [in the commit you mentioned](https://github.com/mikaelbr/node-notifier/commit/61fafc50c387fab2c53f3883af7d53f53209b0c3) Node notifier was using an older version of Snoretoast that was 275KB which would be fine. However, Snoretoast is now 2 binaries (32-bit and 64-bit) and each are around 2MB (rather than Toaster's tiny 14KB size). 😬 Snoretoast seems to work great from the testing I've done, but adding 4MB to every package that uses JoliNotif doesn't seem like a good solution.

**Comment by pyrech** [comment]
Hey @owenvoke, sadly I missed your previous comment and just created a new Notifier based on Snoretoast in #76.

I agree that adding 4MB of binaries to this package is far from perfect but I think it's the best fix I found until now.

I just tested with using the 32-bit binary on my x64 Windows computer and it worked. So I guess we could only add the x86 binary and avoid the 2.5MB of the x64 version. What do you think?

**Comment by owenvoke** [comment]
@pyrech, if the x86 version works fine on x64, then I think it would be perfect to include only the x86 version and this can always be updated if necessary! Thanks for opening a PR.
