### ISSUE TITLE
rtl support

### ISSUE THREAD

**Issue by afsheen1** [jolicode/JoliNotif#61]
Appreciated your hard work, and it's nice project... 

just tested with win 7 working fine.. if possible to add rtl support in setoption method.

or if possible kindly provide some hints to do it.

thanks

**Comment by pyrech** [comment]
Hi, thanks for your feedback :slightly_smiling_face: 

Just to be sure, are you talking about Right To Left languages? If yes, I'm not certain we can do anything here. Because JoliNotif only use the notifiers available on your system and delegates them the role of displaying the desktop notification. As JoliNotif does not make any assumption about the content, I think the issue is probably located inside the notifier used instead.

If you are running Windows 7, then it's probably [Notifu](http://www.paralint.com/projects/notifu/). But the project does not seem really active: http://www.paralint.com/projects/notifu/changelog.html
I found a page displaying the mail of the developer, you could try to contact him if you will: http://www.paralint.com/projects/notifu/download.html

Please feel free to reopen the issue if you get more information or need further help :wink:
