### ISSUE TITLE
Change "SnoreToast"

### ISSUE THREAD

**Issue by Jaraso17** [jolicode/JoliNotif#87]
Hi,

is it possible to change the "SnoreToast"-text within the notifications on windows?

Regards
Philipp

**Comment by pyrech** [comment]
Hi,

It looks like the [SnoreToast](https://github.com/KDE/snoretoast) project support to brand their notification but it requires to run a cmd in order to create a startMenu shortcut to make it possible (cf their readme).

Additionnaly, we would need to update our [SnoreToastNotifier](https://github.com/jolicode/JoliNotif/blob/main/src/Notifier/SnoreToastNotifier.php#L78-L95) to pass the `--appID` to the embedded .exe binary (no need to create a new property inside `Notification` class, we can reuse its `options` property).

Is it something you would like to try?

**Comment by Jaraso17** [comment]
Hi,

thanks for the hint.

I think I will try this out for me.
Thank you very much!
